// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClGjnkLSbiuCUi3dSVpZ_f5OyYFkSo3Vs',
    appId: '1:164031717600:web:b140244301372a59beb085',
    messagingSenderId: '164031717600',
    projectId: 'flash-chat-0501',
    authDomain: 'flash-chat-0501.firebaseapp.com',
    storageBucket: 'flash-chat-0501.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qn5JyqH5qXu9W_py6bu68R8znuqkYjo',
    appId: '1:164031717600:android:abbe86072df8ea76beb085',
    messagingSenderId: '164031717600',
    projectId: 'flash-chat-0501',
    storageBucket: 'flash-chat-0501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdIY1EjjVrBSbnkgsr8_NdiFNxC1C3dyw',
    appId: '1:164031717600:ios:ac5fafbe55e92d4fbeb085',
    messagingSenderId: '164031717600',
    projectId: 'flash-chat-0501',
    storageBucket: 'flash-chat-0501.appspot.com',
    iosBundleId: 'com.quse.flashChatV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdIY1EjjVrBSbnkgsr8_NdiFNxC1C3dyw',
    appId: '1:164031717600:ios:bccaa136ec34926cbeb085',
    messagingSenderId: '164031717600',
    projectId: 'flash-chat-0501',
    storageBucket: 'flash-chat-0501.appspot.com',
    iosBundleId: 'com.quse.flashChatV2.RunnerTests',
  );
}
